- name: Collect system metrics and update Excel on OneDrive
  hosts: all
  gather_facts: no
  tasks:
    - name: Get uptime
      command: uptime -p
      register: uptime_out

    - name: Get disk usage
      command: df -h --output=pcent / | tail -1
      register: disk_out

    - name: Update Excel on OneDrive
      delegate_to: localhost
      command: >
        python3 update_excel_onedrive.py
        {{ inventory_hostname }}
        "{{ uptime_out.stdout }}"
        "{{ disk_out.stdout }}"
      environment:
        ONEDRIVE_CLIENT_ID: "{{ lookup('env','ONEDRIVE_CLIENT_ID') }}"
        ONEDRIVE_CLIENT_SECRET: "{{ lookup('env','ONEDRIVE_CLIENT_SECRET') }}"
        ONEDRIVE_TENANT_ID: "{{ lookup('env','ONEDRIVE_TENANT_ID') }}"
