    - name: Check /etc/rsyslog.conf file
      shell: "sha1sum /etc/passwd"
      register: passwd_hash
      become: true
      become_user: root
    
    - name: Load passwd_hash backup file
      local_action:
        module: shell
        cmd: 'cat /home/huytq/AutoSecOps/LogChecks/{{ inventory_hostname }}/tmp/sha_passwd.txt'
      register: file_content
    
    - name: Compare Content
      set_fact:
        is_passwd_change_config: >-
          {%- if file_content.stdout == passwd_hash.stdout -%}
            "Same content"
          {%- elif file_content.stdout == "ERROR" -%}
              "Please update file content for the first time"
          {%- elif passwd_hash.stdout == "ERROR" -%}
              "Error when run sha1sum /etc/rsyslog.conf"
          {%- else -%}
               "Passwd different with backup file"
          {%- endif -%}
      ignore_errors: true

    - name: Compare Content Debug
      debug: 
        msg: "Back up content {{file_content.stdout}} : Current content {{passwd_hash.stdout}}"
      when: mode == "dev"
