---
- name: Build report ANM CTY
  hosts: all
  gather_facts: no

  tasks:
    - name: Collect OS Version colum
      include_tasks: ../OSInfo/OS_Version.yml
    
    - name: Build row cho từng host
      set_fact:
        host_report_row: "{{ inventory_hostname }}, {{ os_version | default('N/A') }}"
      delegate_to: localhost

    - name: Debug row của từng host
      debug:
        var: host_report_row
      when: mode == "dev"

    # Tổng hợp tất cả host_report_row thành report_rows (chạy 1 lần)
    - name: Gom tất cả host rows vào report_rows
      set_fact:
        report_rows: >-
          {{
            groups['all']
            | map('extract', hostvars, 'host_report_row')
            | select('defined')
            | list
          }}
      delegate_to: localhost

    - name: Debug full report
      debug:
        var: report_rows
      when: mode == "dev"
      run_once: true
    
    - name: Đảm bảo file CSV có header
      local_action:
        module: copy
        dest: "../../Reports/anm_cty.csv"
        content: "Hostname,OS Version\n"
        force: no
      run_once: true
      delegate_to: localhost
      when: mode == "prod" 
    
    - name: Append OS info của từng host vào CSV
      local_action:
        module: copy
        dest: "../../Reports/anm_cty.csv"
        content: |-
          Hostname,OS,Version
          {% for row in report_rows %}
          {{ row }}
          {% endfor %}
      become: no
      delegate_to: localhost
      when: mode == "prod"
