- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../Configs/autosecops_google_sheet.yml   # file vault chứa google_sheet_creds
  environment:
    LANG: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"

  vars:
    spreadsheet_id: "1f-fHFE18Ipmzl_zyMh5-Jf5Mxn3xsd1fvuIPHn-dj44"
    sheet_name: "Sheet1"
    service_account_file: "../Configs/autosecops_google_sheet.json"

  tasks:
    - name: Đọc update_data từ stdin (pipe)
      debug:
        var: vars
    - name: Gom tất cả extra-vars thành dict update_data
      set_fact:
        update_data: "{{ update_data }}"

    - name: Debug credentials raw
      debug:
        msg: "{{ google_sheet_creds }}"

    - name: Chạy Python update Google Sheet (dev)
      command: >
        python3 ../Actions/update_google_sheet.py
        --spreadsheet_id {{ spreadsheet_id }}
        --sheet_name {{ sheet_name }}
        --service_account_file {{ service_account_file }}
      args:
        stdin: "{{ update_data | to_json }}"    
      environment:
        GOOGLE_SHEET_CREDENTIALS: "{{ google_sheet_creds }}"
        MODE: "dev"  
      when: mode == "dev"

    - name: Chạy Python update Google Sheet (prod)
      command: >
        python3 ../Actions/update_google_sheet.py
        --spreadsheet_id {{ spreadsheet_id }}
        --sheet_name {{ sheet_name }}
      args:
        stdin: "{{ update_data | to_json }}"  
      environment:
        GOOGLE_SHEET_CREDENTIALS: "{{ google_sheet_creds }}"
        MODE: "prod"
      when: mode == "prod"
